spring:
  # Configuração JPA (apenas leitura)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Configuração do banco de dados (master para escrita)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/packagetracking}
    username: ${SPRING_DATASOURCE_USERNAME:app_write}
    password: ${SPRING_DATASOURCE_PASSWORD:app_write}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configuração RabbitMQ
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

# Configuração da aplicação
app:
  # Ativar apenas consumer
  jpa:
    enabled: false
  producer:
    enabled: false
  consumer:
    enabled: true

# Configuração do servidor
server:
  port: 8080

# Logging
logging:
  level:
    com.packagetracking: INFO
    com.packagetracking.command.consumer: DEBUG 