# Configuração otimizada para alto volume de consultas
server:
  port: 8080
  # Timeouts otimizados para alto volume
  connection-timeout: 200
  shutdown: graceful
  graceful-timeout: 2000
  # Configurações de thread pool
  tomcat:
    threads:
      max: 200
      min-spare: 20
    max-connections: 8192
    accept-count: 100
    connection-timeout: 200

spring:
  application:
    name: package-command-high-volume
  
  datasource:
    url: jdbc:mysql://localhost:3306/packagetracking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&initialTimeout=200&socketTimeout=500&connectTimeout=200&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: app_write
    password: app_write
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # Pool otimizado para alto volume
      maximum-pool-size: 200
      minimum-idle: 50
      connection-timeout: 200
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 15000
      validation-timeout: 100
      connection-test-query: SELECT 1
      connection-init-sql: "SELECT 1"
      validation-interval: 15000
      keepalive-time: 30000
      register-mbeans: true
      pool-name: HikariPool-package-command
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        show_sql: false
        format_sql: false
        connection:
          provider_disables_autocommit: false
        # Otimizações para performance
        jdbc.batch_versioned_data: true
        jdbc.batch.builder: legacy
        connection.provider_disables_autocommit: false
        jdbc.timeout: 500
        connection.pool_size: 200
        # Configurações específicas para alto volume
        hibernate.jdbc.fetch_size: 100
        hibernate.jdbc.batch_size: 100
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.batch_versioned_data: true

  # Configurações de timeout para controllers
  mvc:
    async:
      request-timeout: 500 # 500ms para requests assíncronos

app:
  country-code: BR
  
  modules:
    package-controllers-enabled: ${PACKAGE_CONTROLLERS_ENABLED:true}
    tracking-producer-enabled: ${TRACKING_PRODUCER_ENABLED:true}
    tracking-consumer-enabled: ${TRACKING_CONSUMER_ENABLED:true}
  
  fixed-holidays:
    - "01-01"
    - "04-21"
    - "05-01"
    - "09-07"
    - "10-12"
    - "11-02"
    - "11-15"
    - "12-25"

external:
  apis:
    holiday:
      base-url: https://date.nager.at
      timeout:
        connect: 100
        read: 200
        write: 100
    dog:
      base-url: https://dogapi.dog
      timeout:
        connect: 50
        read: 100
        write: 50

feign:
  client:
    config:
      default:
        connect-timeout: 100
        read-timeout: 200
        logger-level: basic
      holiday-api:
        connect-timeout: 100
        read-timeout: 200
        logger-level: basic
      dog-api:
        connect-timeout: 50
        read-timeout: 100
        logger-level: basic
  circuitbreaker:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      date-nager-api:
        sliding-window-size: 50
        minimum-number-of-calls: 20
        permitted-number-of-calls-in-half-open-state: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 1000
        failure-rate-threshold: 20
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 200
      dog-api:
        sliding-window-size: 30
        minimum-number-of-calls: 15
        permitted-number-of-calls-in-half-open-state: 8
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 500
        failure-rate-threshold: 25
        slow-call-rate-threshold: 60
        slow-call-duration-threshold: 100
  retry:
    instances:
      date-nager-api:
        max-attempts: 1
        wait-duration: 20
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
      dog-api:
        max-attempts: 1
        wait-duration: 10
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
  timelimiter:
    instances:
      date-nager-api:
        timeout-duration: 200
        cancel-running-future: true
      dog-api:
        timeout-duration: 100
        cancel-running-future: true
  ratelimiter:
    instances:
      date-nager-api:
        limit-for-period: 100
        limit-refresh-period: 1000
        timeout-duration: 50
      dog-api:
        limit-for-period: 200
        limit-refresh-period: 1000
        timeout-duration: 25

java:
  version: "21"
  virtual-threads:
    enabled: true
    max-count: 50000
    stack-size: "64KB"

rabbitmq:
  config:
    address: ${RABBIT_MQ_ADDRESS:amqp://localhost:5672/packagetracking}
  host: localhost
  port: 5672
  connection-timeout: 200
  requested-heartbeat: 20
  connection:
    timeout: 200
    shutdown-timeout: 200
  template:
    retry:
      enabled: true
      initial-interval: 50
      max-attempts: 1
      max-interval: 100
      multiplier: 1.0
  listener:
    simple:
      concurrency: ${RABBIT_MQ_LISTENER_CONCURRENCY:20}
      max-concurrency: ${RABBIT_MQ_LISTENER_MAX_CONCURRENCY:50}
      default-requeue-rejected: ${RABBIT_MQ_LISTENER_DEFAULT_REQUEUE_REJECTED:false}
      auto-startup: ${RABBIT_MQ_LISTENER_AUTO_STARTUP:true}
      prefetch: ${RABBIT_MQ_LISTENER_PREFETCH:500}
      retry:
        enabled: ${RABBIT_MQ_LISTENER_ENABLED:true}
        initial-interval: ${RABBIT_MQ_LISTENER_INITIAL_INTERVAL:50}
        max-attempts: ${RABBIT_MQ_LISTENER_MAX_ATTEMPTS:1}
        max-interval: ${RABBIT_MQ_LISTENER_MAX_INTERVAL:100}
        multiplier: ${RABBIT_MQ_LISTENER_MULTIPLIER:1}

queue:
  countries: ${QUEUE_COUNTRIES:br,us,ca,mx,ar}
  entity: ${QUEUE_ENTITY:package}
  qualifier: ${QUEUE_QUALIFIER:command}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      hikaricp: true
      jvm: true
      process: true
      system: true
    tags:
      application: package-command-high-volume
      component: database
      operation: write

logging:
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","logger":"%logger{36}","message":"%msg","thread":"%thread","traceId":"%X{traceId}","spanId":"%X{spanId}"}'
  level:
    com.packagetracking: WARN
    org.springframework.web: WARN
    com.packagetracking.command.client: WARN
    com.packagetracking.command.config: WARN 